lib/customizer_web/router.ex
defmodule CustomizerWeb.Router do
  use CustomizerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CustomizerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", ItemController, :index
    post "/", ItemController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", CustomizerWeb do
  #   pipe_through :api
  # end
end

lib/customizer_web/controllers/item_controller.ex
defmodule CustomizerWeb.ItemController do
  use CustomizerWeb, :controller

  import Customizer.TiledItems

  alias Customizer.Textures
  alias Customizer.ZipBuilder

  def index(conn, _params) do
    render conn, "index.html", categories: categories()
  end

  def create(conn, %{"item" => item_params}) do
    sanitized_list = item_params
    |> Map.drop(["password"])
    |> create_tiled_files()

    complete_list = Map.merge(Textures.default_list, sanitized_list)
    |> update_clock_files(item_params)
    |> update_compass_files(item_params)

    {:ok, temp_dir} = ZipBuilder.create_temp_directory(complete_list)
    {:ok, zip} = ZipBuilder.create_zip(temp_dir)

    ZipBuilder.delete_temp_dir(temp_dir)

    conn
    |> put_resp_header("content-disposition", ~s(attachment; filename="#{to_string(zip)}"))
    |> send_file(200, to_string(zip))
  end
  def create(conn, %{}) do
    conn
    |> put_flash(:error, "Please make some selections before creating a texture pack.")
    |> render("index.html", categories: categories())
  end

  def create(_conn) do
    render("index.html")
  end

  defp categories(), do: Textures.categories()

  defp update_clock_files(full_list, item_params) do
    type_name = case item_params["clock_00"] do
                  "items/clock_00/" <> suffix ->  suffix
                  _ -> "default.png"
                end

    full_list
    |> Enum.reduce(%{}, fn({key, item}, acc) ->
      case key do
        "clock_" <> number -> Map.put(acc, key, "items/clock_#{number}/#{type_name}")
        _ -> Map.put(acc, key, item)
      end
    end)
  end

  defp update_compass_files(full_list, item_params) do
    type_name = case item_params["clock_00"] do
      "items/compass_00/" <> suffix ->  suffix
      _ -> "default.png"
    end

    full_list
    |> Enum.reduce(%{}, fn({key, item}, acc) ->
      case key do
        "compass_" <> number -> Map.put(acc, key, "items/compass_#{number}/#{type_name}")
        _ -> Map.put(acc, key, item)
      end
    end)
  end

  defp update_recovery_compass_files(full_list, item_params) do
    type_name = case item_params["clock_00"] do
      "items/recovery_compass_00/" <> suffix ->  suffix
      _ -> "default.png"
    end

    full_list
    |> Enum.reduce(%{}, fn({key, item}, acc) ->
      case key do
        "recovery_compass_" <> number -> Map.put(acc, key, "items/recovery_compass_#{number}/#{type_name}")
        _ -> Map.put(acc, key, item)
      end
    end)
  end

  defp create_tiled_files(item_params) do
    item_params
    |> Enum.reduce(%{}, fn({key, item}, acc) ->
      if top_file?(String.replace(key, "block_", "")) do
        acc = Map.put(acc, key, item)
        Map.put(acc, lower_equiv(key), lower_equiv(item))
      else
        Map.put(acc, key, item)
      end
    end)
  end
end

lib/customizer_web/views/item_view.ex
defmodule CustomizerWeb.ItemView do
  use CustomizerWeb, :view

  import Customizer.TiledItems

  alias Customizer.Textures
  alias Customizer.SaveManager

  def determine_item_template(item) do
    if is_two_tiles?(item) do
      "tiled_items.html"
    else
      "single_items.html"
    end
  end

  def proper_punctuation(item) do
    item
    |> String.split("_")
    |> Enum.map(fn(x) -> String.capitalize(x) end)
    |> Enum.uniq()
    |> Enum.join(" ")
    |> String.replace("Sub ", "")
  end

  def proper_punctuation_for_tiled(item) do
    item
    |> String.split("_")
    |> Enum.map(fn(x) -> String.capitalize(x) end)
    |> Enum.uniq()
    |> Enum.join(" ")
    |> String.replace("Sub ", "")
    |> String.replace("Top", "")
  end

  def remove_subs(item) do
    if Enum.any?(item, fn(x) -> x == "Sub" end) do
      item = remove_subs(Enum.drop(item, 2))
    end
    item
  end

  def default?(item) do
    Regex.match?(~r/default/, item)
  end

  def preload?(socket) do
    socket.assigns != %{}
  end

  def selected_file?(category, item, file, socket) do
    check_preload_assign(socket.assigns, "#{category}/#{item}/#{file}")
  end

  def check_preload_assign(%{keyword: password}, file) do
    SaveManager.verify_selection(password, file)
  end
  def check_preload_assign(_, _) do
    false
  end

  def get_non_custom_images(category) do
    get_images(category)
    |> Enum.filter(fn(x) -> x.custom_category == "" end)
  end

  def select_custom_cat_images(custom_category, category) do
    get_images(category)
    |> Enum.filter(fn(x) -> x.custom_category == custom_category end)
  end

  def get_custom_categories(category) do
    Textures.custom_categories(category)
  end

  def get_images(category) do
    Textures.file_list()[category]
    |> Enum.sort_by(fn(x) -> x.name end)
  end
end

lib/customizer_web/templates/item/category.html.eex
<div id="<%= @category %>_div" class="row expanded">
  <div class="container">
    <%= for custom_category <- get_custom_categories(@category)  do %>
      <label class="expand expanded_custom" for="<%= custom_category %>"><%= proper_punctuation(custom_category) %></label>

      <div id="<%= custom_category %>_div" class="row collapsed">
        <div class="container">
          <%= for sub_category <- select_custom_cat_images(custom_category, @category)  do %>
            <%= render determine_item_template(sub_category.name), item: sub_category.name, files: sub_category.files, category: @category, conn: @conn%>
          <% end %>

          <div id="<%= custom_category %>_div" class="row">
            <label class="expand expanded_custom_footer expanded_custom" for="<%= custom_category %>">Collapse <%= proper_punctuation(custom_category) %></label>
          </div>
        </div>
      </div>
    <% end %>

    <%= for sub_category <- get_non_custom_images(@category)  do %>
      <div>
        <%= render determine_item_template(sub_category.name), item: sub_category.name, files: sub_category.files, category: @category, conn: @conn%>
      </div>
    <% end %>
  </div>
</div>

lib/customizer_web/templates/item/index.html.eex
<body>
  <div class="row">
    <div class="column lightBox">
      <%= render "save_selections.html", conn: @conn%>
    </div>
    <div class="column column-75">
      <div class="lightBox">
        <p>The Wolfhound Customizer is a pet project I use to practice Elixir.  It also provides a useful service by letting
        you build your own custom version of Wolfhound!
        <hr>
        <p><b>Known issues:</b></p>
        <ul>
          <li>If you don't expand the category that contains previously saved selections, you won't get those selections loaded in the final texture pack.
        </ul>

        <p>If you want to let me know about any problems or improvements you'd like to see, come chat with me on the <a href="http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1238892-wolfhound-pack">Wolfhound Minecraft forum thread.</a></p>
        <p>And if you're wanting to report a problem, please tell me what you were doing when it broke and let me know what browser you're using.  That'll help a lot.  Thanks!</p>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="column lightBox">
      <h2>Variants</h2>
      <p>Click on a button to set all the textures to one variation.</p>
    </div>
  </div>

  <div class="spacer"></div>

  <div class="row>
    <div class="column darkBox">
      <label id="default" class="flavorButton">Default</label>
      <label id="asian" class="flavorButton">Asian</label>
      <label id="heavenly" class="flavorButton">Heavenly</label>
      <label id="dungeon" class="flavorButton">Dungeon</label>
      <label id="fairy" class="flavorButton">Fairy</label>
      <label id="fantasy" class="flavorButton">Fantasy</label>
      <label id="classic" class="flavorButton">Classic Medieval</label>
      <label id="early" class="flavorButton">Early Medieval</label>
      <label id="winter" class="flavorButton">Winter</label>
      <label id="fall" class="flavorButton">Fall</label>
      <label id="summer" class="flavorButton">Summer</label>
    </div>
  </div>

  <hr>

  <%= form_for @conn, Routes.item_path(@conn, :create), fn f -> %>
    <%= for category <- @categories do %>
      <label for="<%= category %>" class="expand mainHeader" id="<%= category %>"><%= proper_punctuation(category) %></label>
      <div id="<%= category %>_div" class="row expandContent"></div>
    <% end %>

    <div><%= submit "Create", class: "btn btn-primary" %></div>
  <% end %>

  <hr>

  <div class="row">
      <div class="column lightBox">
        If you don't want to create a pack now, enter a keyword to access your pack later.
        <p><input type="text" id="keyword"></p>
        <p><input type="submit" class="btn btn-primary" id="save"></p>
        <div id="saveResults"></div>
      </div>
    </div>
  </div>
</body>

lib/customizer_web/templates/item/save_selections.html.eex
<h3>Load Selections</h3>
<p>Enter your keyword to access your pack.</p>
<p><input type="text" id="keywordLoad"></p>
<p><input type="submit" class="btn btn-primary" id="load"></p>
<div id="loadResults"></div>

lib/customizer_web/templates/item/single_items.html.eex
<div class="row">
  <label class="subcat"><%= proper_punctuation(@item) %></label>
</div>

<div class="row">
  <%= for file <- @files do %>
      <label id="<%= @item %>">

      <%= cond do %>
        <%= preload?(@conn) && selected_file?(@category, @item, file, @conn) -> %>
            <%= radio_button :item, String.to_atom("#{@category}_#{@item}"), "#{@category}/#{@item}/#{file}", checked: "checked" %>
          <%= !preload?(@conn) && default?(file) -> %>
            <%= radio_button :item, String.to_atom("#{@category}_#{@item}"), "#{@category}/#{@item}/#{file}", checked: "checked" %>
        <%= true -> %>
          <%= radio_button :item, String.to_atom("#{@category}_#{@item}"), "#{@category}/#{@item}/#{file}" %>
      <% end %>

        <img src="<%= Routes.static_path(@conn, "/images/#{@category}/#{@item}/#{file}") %>">

        <br>
        <%= if Enum.member?(["gui", "entity", "models", "painting"], @category) do %>
          <a href="<%= Routes.static_path(@conn, "/images/#{@category}/#{@item}/#{file}") %>" data-lightbox="image-<%= "#{@category}-#{@item}" %>"><font class="small-link">enlarge</font></a>
        <% end %>
      </label>
  <% end %>
</div>

lib/customizer_web/templates/item/tiled_items.html.eex
<%= if top_file?(@item) do %>
  <div class="row">
      <label class="subcat"><%= proper_punctuation(@item) %></label>
  </div>

  <div class="row">
    <%= for file <- @files do %>
      <label id="<%= @item %>">

        <%= cond do %>
          <%= preload?(@conn) && selected_file?(@category, @item, file, @conn) -> %>
              <%= radio_button :item, String.to_atom("#{@category}_#{@item}"), "#{@category}/#{@item}/#{file}", checked: "checked" %>
            <%= !preload?(@conn) && default?(file) -> %>
              <%= radio_button :item, String.to_atom("#{@category}_#{@item}"), "#{@category}/#{@item}/#{file}", checked: "checked" %>
          <%= true -> %>
            <%= radio_button :item, String.to_atom("#{@category}_#{@item}"), "#{@category}/#{@item}/#{file}" %>
        <% end %>

        <div class="doubleTileDiv">
          <img src="<%= Routes.static_path(@conn, "/images/#{@category}/#{@item}/#{file}") %>">
          <br>
          <img src="<%= Routes.static_path(@conn, "/images/#{@category}/#{lower_equiv(@item)}/#{file}") %>">
        </div>
      </label>
    <% end %>
  </div>
<% end %>